/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	introSidebar: [{type: 'autogenerated', dirName: 'intro'}],
	algebraSidebar: [{type: 'autogenerated', dirName: 'math/algebra'}],
	geometrySidebar: [{type: 'autogenerated', dirName: 'math/geometry'}],
	mathmiscSidebar: [{type: 'autogenerated', dirName: 'math/misc'}],

	mechanicsSidebar: [{type: 'autogenerated', dirName: 'physics/mechanics'}],
	electromagnetismSidebar: [{type: 'autogenerated', dirName: 'physics/electromagnetism'}],
	physicsmiscSidebar: [{type: 'autogenerated', dirName: 'physics/misc'}],
	topicSidebar: [{type: 'autogenerated', dirName: 'physics/topic'}],

	elementSidebar: [{type: 'autogenerated', dirName: 'chemistry/element'}],
	kineticsSidebar: [{type: 'autogenerated', dirName: 'chemistry/kinetics'}],
	structureSidebar: [{type: 'autogenerated', dirName: 'chemistry/structure'}],
	organicSidebar: [{type: 'autogenerated', dirName: 'chemistry/organic'}],

	// But you can create a sidebar manually
	/*
	tutorialSidebar: [
		'intro',
		'hello',
		{
		type: 'category',
		label: 'Tutorial',
		items: ['tutorial-basics/create-a-document'],
		},
	],
	*/
};

export default sidebars;
