export default {
	"\\*": "\\color{red}",
	"(": "\\left\\lparen",
	")": "\\right\\rparen",
	"[": "\\left\\lbrack",
	"]": "\\right\\rbrack",
	"\\{": "\\left\\lbrace",
	"\\}": "\\right\\rbrace",
	"\\la": "\\left\\langle",
	"\\ra": "\\right\\rangle",
	"\\lv": "\\left\\lvert",
	"\\rv": "\\right\\rvert",
	"\\df": "\\dfrac",
	"\\fr": "\\frac",
	"\\d": "\\mathop{}\\!\\mathrm{d}",
	"\\bal": "\\begin{aligned}",
	"\\eal": "\\end{aligned}",
	"\\bcs": "\\begin{cases}",
	"\\ecs": "\\end{cases}",
	"\\red": "\\textcolor{red}{#1}",
	"\\nimplies": "\\mathrel{\\mathclap{\\qquad/}{\\implies}}",
	"\\nimpliedby": "\\mathrel{\\mathclap{\\qquad\\enspace/}{\\impliedby}}",
	"\\niff": "\\mathrel{\\mathclap{\\qquad\\enspace/}{\\iff}}",
	"\\xto": "\\xrightarrow",
	"\\xgets": "\\xleftarrow",
	"\\xdarr": "\\darr \\raisebox{.3ex}{$\\scriptstyle {#1}$}",
	"\\xudarr": "\\raisebox{.3ex}{$\\scriptstyle {#1}$} \\upharpoonleft\\!\\downharpoonright \\raisebox{.3ex}{$\\scriptstyle {#2}$}"
}
