export default {
	"\\*": "\\color{red}",
	"\\red": "\\textcolor{red}{#1}",
	"\\(": "\\left\\lparen",
	"\\)": "\\right\\rparen",
	"\\[": "\\left\\lbrack",
	"\\]": "\\right\\rbrack",
	"\\{": "\\left\\lbrace",
	"\\}": "\\right\\rbrace",
	"\\la": "\\left\\langle",
	"\\ra": "\\right\\rangle",
	"\\lc": "\\left\\lceil",
	"\\rc": "\\right\\rceil",
	"\\lf": "\\left\\lfloor",
	"\\rf": "\\right\\rfloor",
	"\\lv": "\\left\\lvert",
	"\\rv": "\\right\\rvert",
	"\\bal": "\\begin{aligned}",
	"\\eal": "\\end{aligned}",
	"\\bcs": "\\begin{cases}",
	"\\ecs": "\\end{cases}",
	"\\df": "\\dfrac",
	"\\fr": "\\frac",
	"\\d": "\\mathop{}\\!\\mathrm{d}",
	"\\e": "\\mathrm{e}",
	"\\i": "\\mathrm{i}",
	"\\C": "\\mathbb{C}",
	"\\R": "\\mathbb{R}",
	"\\Q": "\\mathbb{Q}",
	"\\Z": "\\mathbb{Z}",
	"\\N": "\\mathbb{N}",
	"\\P": "\\mathbb{P}",
	"\\nimplies": "\\mathrel{\\mathclap{\\qquad/}{\\implies}}",
	"\\nimpliedby": "\\mathrel{\\mathclap{\\qquad\\enspace/}{\\impliedby}}",
	"\\niff": "\\mathrel{\\mathclap{\\qquad\\enspace/}{\\iff}}",
	"\\xto": "\\xrightarrow",
	"\\xgets": "\\xleftarrow",
	"\\xdarr": "\\darr \\raisebox{.3ex}{$\\scriptstyle {#1}$}",
	"\\xudarr": "\\raisebox{.3ex}{$\\scriptstyle {#1}$} \\upharpoonleft\\!\\downharpoonright \\raisebox{.3ex}{$\\scriptstyle {#2}$}",
	"\\card": "\\operatorname{card}",
	"\\na": "N_{\\mathrm A}",
	"\\mr": "M_{\\mathrm r}",
	"\\vm": "V_{\\mathrm m}"
}
